name: CI/CD Catalog Service

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push catalog-service Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./catalog-service
        file: ./catalog-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/catalog-service:0.2

    - name: Build and Push shopping-cart-service Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./shopping-cart-service
        file: ./shopping-cart-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/shopping-cart-service:0.1

    - name: Setup kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
